import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}
        <footer>
          {/* Copyright Notice */}
          <div className="py-2 px-6 bg-transparent  text-gray-500 fixed bottom-0">
            &copy; {new Date().getFullYear()} Akramul Jakir
          </div>
        </footer>
      </body>
    </html>
  );
}
